require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::ArticlesController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Article. As you add validations to Admin::Article, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::ArticlesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_articles as @admin_articles" do
      article = Admin::Article.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_articles).should eq([article])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_article as @admin_article" do
      article = Admin::Article.create! valid_attributes
      get :show, {:id => article.to_param}, valid_session
      assigns(:admin_article).should eq(article)
    end
  end

  describe "GET new" do
    it "assigns a new admin_article as @admin_article" do
      get :new, {}, valid_session
      assigns(:admin_article).should be_a_new(Admin::Article)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_article as @admin_article" do
      article = Admin::Article.create! valid_attributes
      get :edit, {:id => article.to_param}, valid_session
      assigns(:admin_article).should eq(article)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Article" do
        expect {
          post :create, {:admin_article => valid_attributes}, valid_session
        }.to change(Admin::Article, :count).by(1)
      end

      it "assigns a newly created admin_article as @admin_article" do
        post :create, {:admin_article => valid_attributes}, valid_session
        assigns(:admin_article).should be_a(Admin::Article)
        assigns(:admin_article).should be_persisted
      end

      it "redirects to the created admin_article" do
        post :create, {:admin_article => valid_attributes}, valid_session
        response.should redirect_to(Admin::Article.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_article as @admin_article" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Article.any_instance.stub(:save).and_return(false)
        post :create, {:admin_article => { "title" => "invalid value" }}, valid_session
        assigns(:admin_article).should be_a_new(Admin::Article)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Article.any_instance.stub(:save).and_return(false)
        post :create, {:admin_article => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_article" do
        article = Admin::Article.create! valid_attributes
        # Assuming there are no other admin_articles in the database, this
        # specifies that the Admin::Article created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Article.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => article.to_param, :admin_article => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested admin_article as @admin_article" do
        article = Admin::Article.create! valid_attributes
        put :update, {:id => article.to_param, :admin_article => valid_attributes}, valid_session
        assigns(:admin_article).should eq(article)
      end

      it "redirects to the admin_article" do
        article = Admin::Article.create! valid_attributes
        put :update, {:id => article.to_param, :admin_article => valid_attributes}, valid_session
        response.should redirect_to(article)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_article as @admin_article" do
        article = Admin::Article.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Article.any_instance.stub(:save).and_return(false)
        put :update, {:id => article.to_param, :admin_article => { "title" => "invalid value" }}, valid_session
        assigns(:admin_article).should eq(article)
      end

      it "re-renders the 'edit' template" do
        article = Admin::Article.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Article.any_instance.stub(:save).and_return(false)
        put :update, {:id => article.to_param, :admin_article => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_article" do
      article = Admin::Article.create! valid_attributes
      expect {
        delete :destroy, {:id => article.to_param}, valid_session
      }.to change(Admin::Article, :count).by(-1)
    end

    it "redirects to the admin_articles list" do
      article = Admin::Article.create! valid_attributes
      delete :destroy, {:id => article.to_param}, valid_session
      response.should redirect_to(admin_articles_url)
    end
  end

end
