require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Trader::BillsController do

  # This should return the minimal set of attributes required to create a valid
  # Trader::Bill. As you add validations to Trader::Bill, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "price" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Trader::BillsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all trader_bills as @trader_bills" do
      bill = Trader::Bill.create! valid_attributes
      get :index, {}, valid_session
      assigns(:trader_bills).should eq([bill])
    end
  end

  describe "GET show" do
    it "assigns the requested trader_bill as @trader_bill" do
      bill = Trader::Bill.create! valid_attributes
      get :show, {:id => bill.to_param}, valid_session
      assigns(:trader_bill).should eq(bill)
    end
  end

  describe "GET new" do
    it "assigns a new trader_bill as @trader_bill" do
      get :new, {}, valid_session
      assigns(:trader_bill).should be_a_new(Trader::Bill)
    end
  end

  describe "GET edit" do
    it "assigns the requested trader_bill as @trader_bill" do
      bill = Trader::Bill.create! valid_attributes
      get :edit, {:id => bill.to_param}, valid_session
      assigns(:trader_bill).should eq(bill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Trader::Bill" do
        expect {
          post :create, {:trader_bill => valid_attributes}, valid_session
        }.to change(Trader::Bill, :count).by(1)
      end

      it "assigns a newly created trader_bill as @trader_bill" do
        post :create, {:trader_bill => valid_attributes}, valid_session
        assigns(:trader_bill).should be_a(Trader::Bill)
        assigns(:trader_bill).should be_persisted
      end

      it "redirects to the created trader_bill" do
        post :create, {:trader_bill => valid_attributes}, valid_session
        response.should redirect_to(Trader::Bill.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trader_bill as @trader_bill" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trader::Bill.any_instance.stub(:save).and_return(false)
        post :create, {:trader_bill => { "price" => "invalid value" }}, valid_session
        assigns(:trader_bill).should be_a_new(Trader::Bill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trader::Bill.any_instance.stub(:save).and_return(false)
        post :create, {:trader_bill => { "price" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trader_bill" do
        bill = Trader::Bill.create! valid_attributes
        # Assuming there are no other trader_bills in the database, this
        # specifies that the Trader::Bill created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Trader::Bill.any_instance.should_receive(:update_attributes).with({ "price" => "" })
        put :update, {:id => bill.to_param, :trader_bill => { "price" => "" }}, valid_session
      end

      it "assigns the requested trader_bill as @trader_bill" do
        bill = Trader::Bill.create! valid_attributes
        put :update, {:id => bill.to_param, :trader_bill => valid_attributes}, valid_session
        assigns(:trader_bill).should eq(bill)
      end

      it "redirects to the trader_bill" do
        bill = Trader::Bill.create! valid_attributes
        put :update, {:id => bill.to_param, :trader_bill => valid_attributes}, valid_session
        response.should redirect_to(bill)
      end
    end

    describe "with invalid params" do
      it "assigns the trader_bill as @trader_bill" do
        bill = Trader::Bill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trader::Bill.any_instance.stub(:save).and_return(false)
        put :update, {:id => bill.to_param, :trader_bill => { "price" => "invalid value" }}, valid_session
        assigns(:trader_bill).should eq(bill)
      end

      it "re-renders the 'edit' template" do
        bill = Trader::Bill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trader::Bill.any_instance.stub(:save).and_return(false)
        put :update, {:id => bill.to_param, :trader_bill => { "price" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trader_bill" do
      bill = Trader::Bill.create! valid_attributes
      expect {
        delete :destroy, {:id => bill.to_param}, valid_session
      }.to change(Trader::Bill, :count).by(-1)
    end

    it "redirects to the trader_bills list" do
      bill = Trader::Bill.create! valid_attributes
      delete :destroy, {:id => bill.to_param}, valid_session
      response.should redirect_to(trader_bills_url)
    end
  end

end
