require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe User::MpUsersController do

  # This should return the minimal set of attributes required to create a valid
  # User::MpUser. As you add validations to User::MpUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "shortOpenID" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # User::MpUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all user_mp_users as @user_mp_users" do
      mp_user = User::MpUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:user_mp_users).should eq([mp_user])
    end
  end

  describe "GET show" do
    it "assigns the requested user_mp_user as @user_mp_user" do
      mp_user = User::MpUser.create! valid_attributes
      get :show, {:id => mp_user.to_param}, valid_session
      assigns(:user_mp_user).should eq(mp_user)
    end
  end

  describe "GET new" do
    it "assigns a new user_mp_user as @user_mp_user" do
      get :new, {}, valid_session
      assigns(:user_mp_user).should be_a_new(User::MpUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_mp_user as @user_mp_user" do
      mp_user = User::MpUser.create! valid_attributes
      get :edit, {:id => mp_user.to_param}, valid_session
      assigns(:user_mp_user).should eq(mp_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new User::MpUser" do
        expect {
          post :create, {:user_mp_user => valid_attributes}, valid_session
        }.to change(User::MpUser, :count).by(1)
      end

      it "assigns a newly created user_mp_user as @user_mp_user" do
        post :create, {:user_mp_user => valid_attributes}, valid_session
        assigns(:user_mp_user).should be_a(User::MpUser)
        assigns(:user_mp_user).should be_persisted
      end

      it "redirects to the created user_mp_user" do
        post :create, {:user_mp_user => valid_attributes}, valid_session
        response.should redirect_to(User::MpUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_mp_user as @user_mp_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        User::MpUser.any_instance.stub(:save).and_return(false)
        post :create, {:user_mp_user => { "shortOpenID" => "invalid value" }}, valid_session
        assigns(:user_mp_user).should be_a_new(User::MpUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        User::MpUser.any_instance.stub(:save).and_return(false)
        post :create, {:user_mp_user => { "shortOpenID" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_mp_user" do
        mp_user = User::MpUser.create! valid_attributes
        # Assuming there are no other user_mp_users in the database, this
        # specifies that the User::MpUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        User::MpUser.any_instance.should_receive(:update_attributes).with({ "shortOpenID" => "MyString" })
        put :update, {:id => mp_user.to_param, :user_mp_user => { "shortOpenID" => "MyString" }}, valid_session
      end

      it "assigns the requested user_mp_user as @user_mp_user" do
        mp_user = User::MpUser.create! valid_attributes
        put :update, {:id => mp_user.to_param, :user_mp_user => valid_attributes}, valid_session
        assigns(:user_mp_user).should eq(mp_user)
      end

      it "redirects to the user_mp_user" do
        mp_user = User::MpUser.create! valid_attributes
        put :update, {:id => mp_user.to_param, :user_mp_user => valid_attributes}, valid_session
        response.should redirect_to(mp_user)
      end
    end

    describe "with invalid params" do
      it "assigns the user_mp_user as @user_mp_user" do
        mp_user = User::MpUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        User::MpUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => mp_user.to_param, :user_mp_user => { "shortOpenID" => "invalid value" }}, valid_session
        assigns(:user_mp_user).should eq(mp_user)
      end

      it "re-renders the 'edit' template" do
        mp_user = User::MpUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        User::MpUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => mp_user.to_param, :user_mp_user => { "shortOpenID" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_mp_user" do
      mp_user = User::MpUser.create! valid_attributes
      expect {
        delete :destroy, {:id => mp_user.to_param}, valid_session
      }.to change(User::MpUser, :count).by(-1)
    end

    it "redirects to the user_mp_users list" do
      mp_user = User::MpUser.create! valid_attributes
      delete :destroy, {:id => mp_user.to_param}, valid_session
      response.should redirect_to(user_mp_users_url)
    end
  end

end
