require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe User::PostsController do

  # This should return the minimal set of attributes required to create a valid
  # User::Post. As you add validations to User::Post, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "content" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # User::PostsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all user_posts as @user_posts" do
      post = User::Post.create! valid_attributes
      get :index, {}, valid_session
      assigns(:user_posts).should eq([post])
    end
  end

  describe "GET show" do
    it "assigns the requested user_post as @user_post" do
      post = User::Post.create! valid_attributes
      get :show, {:id => post.to_param}, valid_session
      assigns(:user_post).should eq(post)
    end
  end

  describe "GET new" do
    it "assigns a new user_post as @user_post" do
      get :new, {}, valid_session
      assigns(:user_post).should be_a_new(User::Post)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_post as @user_post" do
      post = User::Post.create! valid_attributes
      get :edit, {:id => post.to_param}, valid_session
      assigns(:user_post).should eq(post)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new User::Post" do
        expect {
          post :create, {:user_post => valid_attributes}, valid_session
        }.to change(User::Post, :count).by(1)
      end

      it "assigns a newly created user_post as @user_post" do
        post :create, {:user_post => valid_attributes}, valid_session
        assigns(:user_post).should be_a(User::Post)
        assigns(:user_post).should be_persisted
      end

      it "redirects to the created user_post" do
        post :create, {:user_post => valid_attributes}, valid_session
        response.should redirect_to(User::Post.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_post as @user_post" do
        # Trigger the behavior that occurs when invalid params are submitted
        User::Post.any_instance.stub(:save).and_return(false)
        post :create, {:user_post => { "content" => "invalid value" }}, valid_session
        assigns(:user_post).should be_a_new(User::Post)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        User::Post.any_instance.stub(:save).and_return(false)
        post :create, {:user_post => { "content" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_post" do
        post = User::Post.create! valid_attributes
        # Assuming there are no other user_posts in the database, this
        # specifies that the User::Post created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        User::Post.any_instance.should_receive(:update_attributes).with({ "content" => "MyString" })
        put :update, {:id => post.to_param, :user_post => { "content" => "MyString" }}, valid_session
      end

      it "assigns the requested user_post as @user_post" do
        post = User::Post.create! valid_attributes
        put :update, {:id => post.to_param, :user_post => valid_attributes}, valid_session
        assigns(:user_post).should eq(post)
      end

      it "redirects to the user_post" do
        post = User::Post.create! valid_attributes
        put :update, {:id => post.to_param, :user_post => valid_attributes}, valid_session
        response.should redirect_to(post)
      end
    end

    describe "with invalid params" do
      it "assigns the user_post as @user_post" do
        post = User::Post.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        User::Post.any_instance.stub(:save).and_return(false)
        put :update, {:id => post.to_param, :user_post => { "content" => "invalid value" }}, valid_session
        assigns(:user_post).should eq(post)
      end

      it "re-renders the 'edit' template" do
        post = User::Post.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        User::Post.any_instance.stub(:save).and_return(false)
        put :update, {:id => post.to_param, :user_post => { "content" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_post" do
      post = User::Post.create! valid_attributes
      expect {
        delete :destroy, {:id => post.to_param}, valid_session
      }.to change(User::Post, :count).by(-1)
    end

    it "redirects to the user_posts list" do
      post = User::Post.create! valid_attributes
      delete :destroy, {:id => post.to_param}, valid_session
      response.should redirect_to(user_posts_url)
    end
  end

end
